### ISSUE TITLE
Update for EasyRSA 3.0.1

### ISSUE THREAD

**Issue by SomeEarthling** [pl48415/openvpn-install-advanced#14]
Update to use the rewritten, restructured, streamlined [EasyRSA3](https://github.com/OpenVPN/easy-rsa)

Thanks so much for your effort.

Note: I'm not a programmer :( ; can't contribute.

**Comment by pl48415** [comment]
I don't think there is a need to update to 3.0.1 since it doesn't include any functional updates.

**Comment by SomeEarthling** [comment]
I just hope you add it to a to-do list :)
I think eventually the project has to utilize latest scripts to avoid any incompatibilities or vulns made by old scripts, if any.

But yeah, you're the boss. Not my place.

I'm setting my OpenVPN with EasyRSA3. If it worked then great, if it didn't I'll use this automated script and swallow my pride.

**Comment by pl48415** [comment]
I will add it to my to-do list. I'll have to test and then add it to the script. Thank you for suggestion, it is very much appreciated.
