### ISSUE TITLE
The connection stucks on WAIT

### ISSUE THREAD

**Issue by SquirrelCoder** [pl48415/openvpn-install-advanced#9]
Tue Jan 12 13:50:38 2016 OpenVPN 2.3.10 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [PKCS11] [IPv6] built on Jan  4 2016
Tue Jan 12 13:50:38 2016 Windows version 6.2 (Windows 8 or greater)
Tue Jan 12 13:50:38 2016 library versions: OpenSSL 1.0.1q 3 Dec 2015, LZO 2.09
Tue Jan 12 13:50:38 2016 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Tue Jan 12 13:50:38 2016 Need hold release from management interface, waiting...
Tue Jan 12 13:50:39 2016 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Tue Jan 12 13:50:39 2016 MANAGEMENT: CMD 'state on'
Tue Jan 12 13:50:39 2016 MANAGEMENT: CMD 'log all on'
Tue Jan 12 13:50:39 2016 MANAGEMENT: CMD 'hold off'
Tue Jan 12 13:50:39 2016 MANAGEMENT: CMD 'hold release'
Tue Jan 12 13:50:39 2016 Control Channel Authentication: tls-auth using INLINE static key file
Tue Jan 12 13:50:39 2016 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 12 13:50:39 2016 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 12 13:50:39 2016 Socket Buffers: R=[65536->65536] S=[65536->65536]
Tue Jan 12 13:50:39 2016 UDPv4 link local: [undef]
Tue Jan 12 13:50:39 2016 UDPv4 link remote: [AF_INET]88.150.238.141:1194
Tue Jan 12 13:50:39 2016 MANAGEMENT: >STATE:1452594039,WAIT,,,

The connection will Stuck on WAIT and doesn't go further I have allows the port 1194 on my Server too. using the command: ufw allow 1194
VPS: Ubuntu 14.04 X64

**Comment by zabullet** [comment]
Hi Willi,

This isn't an issue with the script so you'll need to engage the OpenVPN community to solve it.

As a guess I'd say that there is a firewall between yourself and your server that is blocking UDP.

Did you try installing OpenVPN with TCP and trying that?

Regards,

Daniel

**Comment by SquirrelCoder** [comment]
I'm so so sorry, the problem was with my server. I have rebooted the server and now everything works perfectly.
